[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm-9_x', 'openssl']
aptPkgs = ['curl', 'ca-certificates', 'ffmpeg']

[phases.install]
cmds = [
  'pnpm install'
]

[phases.build]
cmds = [
  'pnpm run build',
  'mkdir -p .next/standalone/public',
  'cp -r public/* .next/standalone/public/ || true',
  'mkdir -p .next/standalone/.next/static',
  'cp -r .next/static/* .next/standalone/.next/static/ || true',
  'curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux -o .next/standalone/yt-dlp',
  'chmod a+rx .next/standalone/yt-dlp'
]

[start]
cmd = "node .next/standalone/server.js"
